server:
  port: 8022
spring:
  #app name
  application:
    name: rabbitmq-consumer
  #config rabbitMq server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    #victual host
    virtual-host: my_vhost
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: auto
